### ISSUE TITLE
cannot launch app with 'react-native run-ios'

### ISSUE THREAD

**Issue by hoebat** [alwx/luno-react-native#19]
I'm getting the following error:

```

** BUILD FAILED **


The following build commands failed:
       	CompileC /Users/chris/Development/buffer/luno-react-native/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/luno.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/chris/Development/buffer/luno-react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/luno.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at _runIOS (/Users/chris/Development/buffer/luno-react-native/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at /Users/chris/Development/buffer/luno-react-native/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/chris/Development/buffer/luno-react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/chris/Development/buffer/luno-react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/chris/Development/buffer/luno-react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/chris/Development/buffer/luno-react-native/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/chris/Development/buffer/luno-react-native/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)
```

**Comment by konato** [comment]
Getting  the same error.

**Comment by theronic** [comment]
I managed to solve this by upgrading react-native using the Git method
